# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name compute_cond_var
#' @noRd
compute_cond_var <- function(gamma, model) {
    .Call(`_gctsc_compute_cond_var`, gamma, model)
}

#' @noRd
ptmvn_tmet <- function(args) {
    .Call(`_gctsc_ptmvn_tmet`, args)
}

#' @noRd
ptmvn_ghk <- function(args) {
    .Call(`_gctsc_ptmvn_ghk`, args)
}

ptmvt_tmet <- function(args) {
    .Call(`_gctsc_ptmvt_tmet`, args)
}

ptmvmn_ghk <- function(args) {
    .Call(`_gctsc_ptmvmn_ghk`, args)
}

#' @noRd
ptmvt_ghk <- function(args) {
    .Call(`_gctsc_ptmvt_ghk`, args)
}

#' @noRd
ptmvn_ce <- function(gamma, model) {
    .Call(`_gctsc_ptmvn_ce`, gamma, model)
}

#' @noRd
ptmvt_ce <- function(gamma, model) {
    .Call(`_gctsc_ptmvt_ce`, gamma, model)
}

#' Compute predictive distribution (internal TMET interface)
#' @noRd
predmvn_ghk <- function(args, model) {
    .Call(`_gctsc_predmvn_ghk`, args, model)
}

#' Compute predictive distribution (internal GHK interface)
#' @noRd
predmvn_tmet <- function(args, model) {
    .Call(`_gctsc_predmvn_tmet`, args, model)
}

predmvt <- function(args, model) {
    .Call(`_gctsc_predmvt`, args, model)
}

rtmvn_ghk <- function(args) {
    .Call(`_gctsc_rtmvn_ghk`, args)
}

rtmvn_tmet <- function(args) {
    .Call(`_gctsc_rtmvn_tmet`, args)
}

rtmvt <- function(args) {
    .Call(`_gctsc_rtmvt`, args)
}

