# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name compute_cond_var
#' @noRd
compute_cond_var <- function(gamma, model) {
    .Call(`_gctsc_compute_cond_var`, gamma, model)
}

#' @noRd
CE_core_recursive <- function(gamma, model) {
    .Call(`_gctsc_CE_core_recursive`, gamma, model)
}

#' Compute MVN rectangle probability via TMET
#' @noRd
ptmvn_tmet <- function(args) {
    .Call(`_gctsc_ptmvn_tmet`, args)
}

#' Compute MVN rectangle probability via GHK
#' @noRd
ptmvn_ghk <- function(args) {
    .Call(`_gctsc_ptmvn_ghk`, args)
}

#' Simulate conditional predictive distribution and compute residuals by GHK
#' @noRd
rtmvn_ghk <- function(args) {
    .Call(`_gctsc_rtmvn_ghk`, args)
}

#' Simulate conditional predictive distribution and compute residuals by TMET
#' @noRd
rtmvn_tmet <- function(args) {
    .Call(`_gctsc_rtmvn_tmet`, args)
}

#' Compute predictive distribution (internal TMET interface)
#' @noRd
predmvn_ghk <- function(args, model) {
    .Call(`_gctsc_predmvn_ghk`, args, model)
}

#' Compute predictive distribution (internal GHK interface)
#' @noRd
predmvn_tmet <- function(args, model) {
    .Call(`_gctsc_predmvn_tmet`, args, model)
}

